#!/usr/bin/env zsh
#
if ((TTY_SHELL == 0)) && [[ ZDOT_THEME_CONSOLE="bhilburn/powerlevel9k" ]] ; then

#POWERLEVEL9K_MODE='modified'
#POWERLEVEL9K_MODE='awesome-patched'
#POWERLEVEL9K_MODE='awesome-fontconfig'
#POWERLEVEL9K_MODE='awesome-fontconfig'
POWERLEVEL9K_MODE='nerdfont-complete'
#POWERLEVEL9K_COLOR_SCHEME='light'
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
#POWERLEVEL9K_RPROMPT_ON_NEWLINE=true
#POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir node_version vcs)
#POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon root_indicator   context dir rbenv vcs)
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(root_indicator context dir dir_writable disk_usage vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(vi_mode status command_execution_time  history time background_jobs virtualenv load)
#POWERLEVEL9K_TIME_FORMAT="%D{%H:%M:%S \uF073 %d/%m/%Y}"
POWERLEVEL9K_TIME_FORMAT="\uF073%D{%d/%m/%Y}"
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_middle"
#POWERLEVEL9K_SHORTEN_DIR_LENGTH=4
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2

POWERLEVEL9K_NODE_VERSION_BACKGROUND='022' 
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""

POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%K{white}%F{black}\uF017 `date +%T` %f%k%F{white}%f "


# Disable dir/git icons
POWERLEVEL9K_HOME_ICON=''
POWERLEVEL9K_HOME_SUB_ICON=''
POWERLEVEL9K_FOLDER_ICON=''

#POWERLEVEL9K_VCS_GIT_ICON=''
POWERLEVEL9K_VCS_STAGED_ICON='\u00b1'
POWERLEVEL9K_VCS_UNTRACKED_ICON='\u25CF'
POWERLEVEL9K_VCS_UNSTAGED_ICON='\u00b1'
POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON='\u2193'
POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON='\u2191'


#POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR="\uE0C0"
#POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR="\uE0C1"
#POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR="\uE0C2"
#POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR="\uE0C3"

fi

if ((TTY_SHELL == 1)); then

setopt promptsubst

# Load theme from OMZ
zplugin snippet "$ZDOT_THEME_TTY"

else
zplugin light "$ZDOT_THEME_CONSOLE"

fi

